branches:
  only:
  - src

install:

script:
  - curl -L https://github.com/Keats/gutenberg/releases/download/v0.2.2/gutenberg-v0.2.2-x86_64-unknown-linux-gnu.tar.gz > gutenberg.tar.gz
  - tar xvzf gutenberg.tar.gz
  - mv gutenberg /tmp/gutenberg && rm gutenberg.tar.gz
  - /tmp/gutenberg build
  - mv public /tmp/public
  - git remote set-url origin $GIT_REMOTE
  - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch
    # create the tacking branches
  - for branch in $(git branch -r|grep -v HEAD) ; do git checkout -qf ${branch#origin/}; done
  - git checkout master
  - rm -r *
  - mv /tmp/public/* ./
  - echo "theduke.at" > CNAME
  - git status
  - git add --all
  - git commit -m "$(echo 'Update ' $(date))"
  - git push
